### ISSUE TITLE
Game becomes unresponsive and a request for fullscreen gameplay

### ISSUE THREAD

**Issue by iamn0tdev** [Creckeryop/Flappy-Bird-Classic-vita#1]
Hi! I really enjoy playing Flappy Birds on Vita. Thank you for porting it to this device.

Two things:
1. There is a bug when sometimes after a lose the game becomes unresponsive. I can't touch the play button even with the X.

2. Can you make the gameplay fullscreen. There was an original version of the game by GEARS called Flappy Birds Family released only on Amazon that can be played in both portrait and landscape mode.

**Comment by Creckeryop** [comment]
1. Is animation of play button is playing if you pressing x? But nothing happens, am I right?
2. Game wasn't designed to support more that 3 tubes on screen, also Amazon version looks crappy, don't sure that landscape mode is harder than portrait one

**Comment by iamn0tdev** [comment]
1. Yes, nothing happens but with both touchsreen and X button. I'm trying to replicate the issue but it doesn´t occur very often. After a lose I can't press play with the X button or touchscreen. Sometimes it takes to many tries.

2. OK.

**Comment by Creckeryop** [comment]
Maybe you will try to hold finger somewhere on screen, and while holding , you will press X?

**Comment by iamn0tdev** [comment]
I am not holding. Maybe my hands get sweaty while playing and the sensitivity of the screen somehow acts like I'm touching it?
[Watch this video](https://streamable.com/667szz)

**Comment by Creckeryop** [comment]
You can download latest release 1.21 i've fixed this, have fun
